version: "3.8"

services:
  db:
    image: mongo:latest
    container_name: mongo_db
    networks:
      - my_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"

  rest-api:
    build: ./rest-api
    container_name: rest_api_service
    depends_on:
      - db
    environment:
      - env=${env}
      - DB_URI=mongodb://root:example@mongo_db:27017/myDatabase?authSource=admin
    networks:
      - my_network
    ports:
      - "1337:1337"
    volumes:
      - ./db:/server/db
      - ./bike-logic:/server/bike-logic
      - ./trips:/server/trips
      - ./simulation:/server/simulation
    command: ["sh", "-c", "npm run ${env:-dev}"]

  admin-web-ui:
    build: ./admin-web-ui
    container_name: admin-web-ui
    environment:
      - SERVER_URL=localhost://1337
    networks:
      - my_network
    ports:
      - "5173:5173"
    command: ["sh", "-c", "npm run dev"]

  user-web-ui:
    build: ./user-web-ui
    container_name: user-web-ui
    environment:
      - SERVER_URL=localhost://1337
    networks:
      - my_network
    ports:
      - "8080:5174"
    command: ["sh", "-c", "npm run dev"]

  user_app:
    image: alfrijde/viav23:fenix_app
    container_name: user_app
    ports:
      - "43785:43785"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
