name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        mongodb-version: ['4.2', '4.4', '5.0']

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.7.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
        


    - run: npm install
      working-directory: services/rest-api
    
    - name: Drop database and import test data
      run: |
        mongo test --eval 'db.dropDatabase()'
        cd testdb
        mongoimport --db test -c bikes --jsonArray addbikes.json
        mongoimport --db test -c users --jsonArray addusers.json
        mongoimport --db test -c cities --jsonArray addcities.json
        mongoimport --db test -c parking_zones --jsonArray addparking.json
        mongoimport --db test -c charging_stations --jsonArray addcharging.json
        mongoimport --db test -c trips --jsonArray addtrips.json
      working-directory: services/rest-api
    
    - run: npm run test
      working-directory: services/rest-api
